name: flutter_native_image
description: Local compatibility patch for native image resize/compress/crop.
version: 0.0.6+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutternativeimage
        pluginClass: FlutterNativeImagePlugin
      ios:
        package: com.example.flutternativeimage
        pluginClass: FlutterNativeImagePlugin
